# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: tests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - main

jobs:
  integration:
      if: "${{ github.event.action != 'labeled' || github.event.label.name == 'tests: run' }}"
      runs-on: [self-hosted, linux, x64]
      name: "integration tests (linux)"
      steps:
        - name: Remove PR label
          if: "${{ github.event.action == 'labeled' && github.event.label.name == 'tests: run' }}"
          uses: actions/github-script@v5
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              try {
                await github.rest.issues.removeLabel({
                  name: 'tests: run',
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number
                });
              } catch (e) {
                console.log('Failed to remove label. Another job may have already removed it!')
              }
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: "1.18"
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Get Secrets
          id: 'secrets'
          uses: 'google-github-actions/get-secretmanager-secrets@v0'
          with:
            secrets: |-
              ALLOYDB_CONN_NAME:alloydb-connector-testing/ALLOYDB_CONN_NAME
              ALLOYDB_CLUSTER_PASS:alloydb-connector-testing/ALLOYDB_CLUSTER_PASS
        - name: Run tests
          env:
            ALLOYDB_DB: 'postgres'
            ALLOYDB_USER: 'postgres'
            ALLOYDB_PASS: '${{ steps.secrets.outputs.ALLOYDB_CLUSTER_PASS }}'
            ALLOYDB_CONNECTION_NAME: '${{ steps.secrets.outputs.ALLOYDB_CONN_NAME }}'
          run: |
            go test -v -race -cover ./tests
  build:
      if: "${{ github.event.action != 'labeled' || github.event.label.name == 'tests: run' }}"
      name: "unit tests"
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
      steps:
        - name: Remove PR label
          if: "${{ github.event.action == 'labeled' && github.event.label.name == 'tests: run' }}"
          uses: actions/github-script@v5
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              try {
                await github.rest.issues.removeLabel({
                  name: 'tests: run',
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number
                });
              } catch (e) {
                console.log('Failed to remove label. Another job may have already removed it!')
              }
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: "1.18"
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run tests
          run: |
            go test -v -race -cover -short ./...
